# Generated by Django 4.0.1 on 2022-02-07 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CONTACT_MODAL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown Name', max_length=100)),
                ('email', models.CharField(default='Unknown Email', max_length=100)),
                ('msg', models.CharField(default='Unknown Msg', max_length=100)),
            ],
        ),
    ]
